package ventanas;
import app.JStatusBar;
import com.sun.glass.events.KeyEvent;
import config.AppConfig;
import static java.time.Clock.system;
import javax.swing.JOptionPane;
import util.AdminIFrame;
/**
 * @author Ferz
 */
public class MainWindow extends javax.swing.JFrame {

    
    private static IProveedores vntProveedores = null;
    private static ISimpleModelo vntModeloMarcaClase = null;
    private static IUsuario vntUsuario = null;
    private static IProducto vntProducto = null;
    private static ICompra vntCompra = null;
    private static IProveedores vntProveedor = null;
    private static ISimpleModelo vntModelo = null;
    public MainWindow() {
        initComponents();
        this.setLocationRelativeTo(null);
        System.out.println(AppConfig.getUsuario().getNombre()+" - "+AppConfig.getUsuario().getApellidos());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        dp = new javax.swing.JDesktopPane();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new JStatusBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Ventas");
        setExtendedState(MAXIMIZED_BOTH);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jButton1.setText("Ventas F1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        getContentPane().add(jButton1);

        jInternalFrame1.setTitle("Nota: Sistema de Ventas");
        jInternalFrame1.setVisible(true);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images1/st.jpg"))); // NOI18N
        jInternalFrame1.getContentPane().add(jLabel1, java.awt.BorderLayout.CENTER);

        dp.add(jInternalFrame1);
        jInternalFrame1.setBounds(30, 170, 680, 600);
        jInternalFrame1.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(dp);

        jPanel1.setPreferredSize(new java.awt.Dimension(549, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 841, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if(vntCompra== null)
        {
            vntCompra = new ICompra();
        }
        AdminIFrame.mostrarVentanaFactura(dp, vntCompra);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_F1){
            if(vntCompra== null)
        {
            vntCompra = new ICompra();
        }
        AdminIFrame.mostrarVentanaFactura(dp, vntCompra);
        }
    }//GEN-LAST:event_jButton1KeyPressed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dp;
    private javax.swing.JButton jButton1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
